- name: Install docker packages
  apt:
    pkg: "{{ docker_pkgs }}"
    state: present

- name: Create docker group
  group:
    name: "{{ docker_user }}"
    state: present
    
- name: Add vagrant user to docker group
  user:
    name: "{{ docker_vagrant }}"
    groups: "{{ docker_group }}"
    append: yes
    
- name: Enable and start docker daemon
  service:
    name: docker
    state: started
    enabled: yes
